# Generated by Django 5.1.6 on 2025-03-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
        ('users', '0004_verificationcode'),
    ]

    operations = [
    ]
