# Generated by Django 5.1.6 on 2025-02-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
