# Generated by Django 5.1.6 on 2025-03-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_advertisement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='advertisementimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
